site_name: Thailand Competitive Programming Wiki
site_url: https://thai-cp.github.io/

nav:
  - Home: index.md
  - ทั่วไป:
    - อะไรคือ Competitive Programming?: general/intro-cp.md
    - สอวน. คอมพิวเตอร์: general/posn.md
    - แหล่งเรียนรู้: general/resources.md
  - Road Map:
    - พื้นฐาน (Basic): roadmap/basic.md
  - การเขียนโปรแกรมเบื้องต้น:
    - บทนำ: prog-basic/index.md
    - วิธีการรันโปรแกรม: prog-basic/run-code.md
    - การเขียนโปรแกรมภาษา C:
      - Hello, World!: prog-basic/c/hello-world.md
      - ตัวแปร ชนิดข้อมูล และตัวดำเนินการ: prog-basic/c/variable.md
      - การส่งออกและนำเข้าข้อมูล: prog-basic/c/input-output.md
      - คำสั่ง if - else: prog-basic/c/if-else.md
      - คำสั่งวนซ้ำ (Loop): prog-basic/c/loops.md
      - ตัวแปรชุด และสายอักขระ: prog-basic/c/array.md
      - ฟังก์ชัน: prog-basic/c/function.md
    - การเขียนโปรแกรมภาษา C++:
      - Hello, World!: prog-basic/cpp/hello-world.md
      - ตัวแปร ชนิดข้อมูล และตัวดำเนินการ: prog-basic/cpp/variable.md
      - การส่งออกและนำเข้าข้อมูล: prog-basic/cpp/input-output.md
      - คำสั่ง if - else: prog-basic/cpp/if-else.md
      - คำสั่งวนซ้ำ (Loop): prog-basic/cpp/loops.md
      - ตัวแปรชุด และสายอักขระ: prog-basic/cpp/array.md
      - ฟังก์ชัน: prog-basic/cpp/function.md
      - STL : prog-basic/cpp/stl.md
  - โครงสร้างข้อมูลและอัลกอริทึมพื้นฐาน:
      - Complexity Analysis: dsa-basic/complexity.md
      - Binary Search: dsa-basic/binary-search.md
      - Sorting Algorithms: dsa-basic/sorting.md
      - Stack: dsa-basic/stack.md
      - Queue: dsa-basic/queue.md
  - โจทย์: problems/index.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to Dark Mode
  features:
    - navigation.tabs
    # - navigation.instant
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - extensions.problem_tag:
  - extensions.problem_info:
  - extensions.problem_all:
  - extensions.resources_tag:
  - extensions.unfinished_tag:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-X3SVQVTEE3

repo_url: https://github.com/thai-cp/thai-cp.github.io/
repo_name: thai-cp/thai-cp.github.io
